# Generated by Django 2.0.4 on 2018-05-29 07:48

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('client_number', models.CharField(blank=True, max_length=100, null=True)),
                ('tin', models.CharField(blank=True, max_length=19, null=True, verbose_name='TIN')),
                ('comp_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Company Type')),
                ('services', models.TextField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, max_length=300, null=True)),
                ('origin', django_countries.fields.CountryField(blank=True, help_text='Country of origin', max_length=2, null=True)),
                ('directors', models.TextField(blank=True, max_length=500, null=True, verbose_name='BOARD OF DIRECTORS')),
                ('company_secretary', models.TextField(blank=True, null=True)),
                ('office', models.TextField(blank=True, null=True, verbose_name='REGISTERED OFFICE')),
                ('bankers', models.TextField(blank=True, null=True)),
                ('lawyers', models.TextField(blank=True, null=True)),
                ('auditors', models.TextField(blank=True, null=True)),
                ('trustees', models.TextField(blank=True, null=True)),
                ('directors_renumenration', models.CharField(blank=True, max_length=200, null=True)),
                ('currency', models.CharField(blank=True, choices=[('USD', 'USD'), ('UGX', 'UGX'), ('GBP', 'GBP')], default='USD', max_length=3, null=True)),
                ('billing_frequency', models.CharField(blank=True, choices=[('Annually', 'Annually'), ('Monthly', 'Monthly'), ('Seasonal', 'Seasonal')], default='Annually', max_length=19, null=True)),
                ('share_capital', models.CharField(blank=True, max_length=200, null=True)),
                ('year_end', models.CharField(blank=True, max_length=10, null=True)),
                ('company_logo', models.ImageField(blank=True, default='image/mazarslogo.jpg', null=True, upload_to='', verbose_name='Logo')),
                ('client', models.BooleanField(default=True, help_text='Currently Client?', verbose_name='Client status')),
                ('telephone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('Email_address', models.CharField(blank=True, max_length=70, null=True)),
                ('is_favorite', models.BooleanField(default=True, verbose_name='Is Client')),
            ],
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Ms', 'Ms'), ('Mr', 'Mr')], max_length=3)),
                ('first_name', models.CharField(max_length=122)),
                ('second_name', models.CharField(max_length=122)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile_number', models.IntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Disengagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('letter', models.FileField(upload_to='', verbose_name='Disengagement letter')),
                ('report', models.FileField(upload_to='', verbose_name='Reports')),
                ('client_comment', models.FileField(upload_to='', verbose_name='client_comments')),
                ('notes', models.CharField(blank=True, max_length=250, null=True, verbose_name='Engagement notes or concerns')),
            ],
        ),
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018)], default=2018, verbose_name='Year')),
                ('reference', models.CharField(blank=True, max_length=122, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('assignment', models.CharField(blank=True, choices=[('Tax compliance', 'Tax compliance'), ('Company secretarial', 'Company secretarial'), ('Audit & assurance', 'Audit & assurance'), ('Tax advisory', 'Tax advisory'), ('Accountancy', 'Accountancy'), ('Consultancy', 'Consultancy'), ('AOS', 'AOS')], max_length=19, null=True, verbose_name='Service')),
                ('letter', models.FileField(blank=True, null=True, upload_to='', verbose_name='Engagement letter')),
                ('engagement_ending', models.DateField(blank=True, null=True, verbose_name='Ending date')),
                ('currency', models.CharField(blank=True, choices=[('USD', 'USD'), ('UGX', 'UGX'), ('GBP', 'GBP')], default='USD', max_length=19, null=True)),
                ('rate', models.PositiveIntegerField(blank=True, null=True, verbose_name='Rate')),
                ('factor', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('active', models.PositiveIntegerField(blank=True, null=True)),
                ('disbursements', models.PositiveIntegerField(blank=True, null=True)),
                ('payment', models.PositiveIntegerField(blank=True, null=True, verbose_name='Payment')),
                ('balance', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(blank=True, choices=[('None', 'None'), ('Pending', 'Pending'), ('Planned', 'Planned'), ('Active', 'Active'), ('Concluded', 'Concluded')], default='None', max_length=122, null=True)),
                ('remarks', models.CharField(blank=True, max_length=1000, null=True)),
                ('type', models.CharField(blank=True, choices=[('Existing', 'Existing'), ('New', 'New')], max_length=12, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='tracker.Client')),
            ],
            options={
                'ordering': ('-date', '-year'),
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=19, verbose_name='Invoice Number')),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('scan', models.FileField(blank=True, null=True, upload_to='', verbose_name='Scanned Invoice')),
                ('reminder', models.DateField(blank=True, null=True, verbose_name='Set Payment Date remainder')),
                ('payments', models.IntegerField(blank=True, null=True)),
                ('engagement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='tracker.Engagement')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=90)),
                ('up_notes', models.CharField(blank=True, max_length=225, null=True)),
                ('notes_file', models.FileField(help_text='(Images, Documents and Audio)', upload_to='')),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Engagement')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('doc', models.FileField(blank=True, null=True, upload_to='', verbose_name='Scanned Receipt')),
                ('date', models.DateField(blank=True, null=True)),
                ('engagement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tracker.Engagement')),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=89, null=True, verbose_name='Name of company or individual')),
                ('source', models.CharField(choices=[('Referal by client', 'Referal by client'), ('Referal by competitor', 'Referal by competitor'), ('Published/Advertized', 'Published/Advertized'), ('Self approach', 'Self approach')], default='Referal by client', max_length=122)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('draft_proposal', models.FileField(blank=True, null=True, upload_to='')),
                ('requirements', models.CharField(blank=True, help_text='Separate by Tab or Commas', max_length=200, null=True)),
                ('qualified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StuffOnJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
                ('first_name', models.CharField(blank=True, max_length=122, null=True)),
                ('last_name', models.CharField(blank=True, max_length=122, null=True)),
                ('section', models.CharField(blank=True, help_text='Section On The Job', max_length=122, null=True)),
                ('engagement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.Engagement')),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018)], unique=True)),
                ('audit', models.PositiveIntegerField(blank=True, null=True)),
                ('aos', models.PositiveIntegerField(blank=True, null=True, verbose_name='AoS')),
                ('taxcom', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tax Complaincy')),
                ('taxadv', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tax Advisory')),
                ('comsec', models.PositiveIntegerField(blank=True, null=True, verbose_name='ComSec')),
                ('consul', models.PositiveIntegerField(blank=True, null=True, verbose_name='Consultancy')),
                ('account', models.PositiveIntegerField(blank=True, null=True, verbose_name='Accountancy')),
                ('audit_new', models.PositiveIntegerField(blank=True, null=True, verbose_name='audit')),
                ('aos_new', models.PositiveIntegerField(blank=True, null=True, verbose_name='AOS')),
                ('taxcom_new', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tax Complaincy')),
                ('taxadv_new', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tax Advisory')),
                ('comsec_new', models.PositiveIntegerField(blank=True, null=True, verbose_name='Company Sec')),
                ('consul_new', models.PositiveIntegerField(blank=True, null=True, verbose_name='Consultancy')),
            ],
            options={
                'ordering': ('-year',),
            },
        ),
        migrations.AddField(
            model_name='disengagement',
            name='engagement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Engagement'),
        ),
    ]
