# Generated by Django 2.0.4 on 2018-05-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='factor',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='rate',
            field=models.PositiveIntegerField(default=1974, verbose_name='Rate'),
            preserve_default=False,
        ),
    ]
