# Generated by Django 2.0.4 on 2018-05-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='balance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
