# Generated by Django 2.0.4 on 2018-05-14 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_remove_payment_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tracker.Invoice'),
        ),
        migrations.AlterField(
            model_name='target',
            name='aos',
            field=models.PositiveIntegerField(default=2, verbose_name='AoS'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='target',
            name='aos_new',
            field=models.PositiveIntegerField(default=2, verbose_name='AoS'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='target',
            name='audit',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='target',
            name='audit_new',
            field=models.PositiveIntegerField(default=1, verbose_name='audit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='target',
            name='comsec',
            field=models.PositiveIntegerField(verbose_name='ComSec'),
        ),
        migrations.AlterField(
            model_name='target',
            name='comsec_new',
            field=models.PositiveIntegerField(verbose_name='ComSec'),
        ),
        migrations.AlterField(
            model_name='target',
            name='consul',
            field=models.PositiveIntegerField(verbose_name='Consul'),
        ),
        migrations.AlterField(
            model_name='target',
            name='consul_new',
            field=models.PositiveIntegerField(verbose_name='Consul'),
        ),
        migrations.AlterField(
            model_name='target',
            name='taxadv',
            field=models.PositiveIntegerField(verbose_name='TaxAdv'),
        ),
        migrations.AlterField(
            model_name='target',
            name='taxadv_new',
            field=models.PositiveIntegerField(verbose_name='TaxAdv'),
        ),
        migrations.AlterField(
            model_name='target',
            name='taxcom',
            field=models.PositiveIntegerField(verbose_name='TaxCom'),
        ),
        migrations.AlterField(
            model_name='target',
            name='taxcom_new',
            field=models.PositiveIntegerField(verbose_name='TaxCom'),
        ),
        migrations.AlterField(
            model_name='target',
            name='year',
            field=models.IntegerField(choices=[(2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018)], unique=True),
        ),
    ]
