# Generated by Django 2.0.4 on 2017-08-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20170801_1351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ()},
        ),
        migrations.AddField(
            model_name='client',
            name='datestamp',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
