# Generated by Django 2.0.4 on 2017-08-01 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20170801_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('-datestamp',)},
        ),
    ]
