# Generated by Django 2.0.4 on 2018-05-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20170801_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='reference',
            field=models.CharField(blank=True, default='2017-01-01', max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='remarks',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='year',
            field=models.IntegerField(choices=[(2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], default=2018, verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='target',
            name='year',
            field=models.IntegerField(choices=[(2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], unique=True),
        ),
    ]
