# Generated by Django 2.0.4 on 2018-05-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_auto_20180530_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='date',
            field=models.DateField(blank=True, default='2017-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='reference',
            field=models.CharField(blank=True, default='/BRJ/', max_length=122, null=True),
        ),
    ]
