# Generated by Django 2.0.4 on 2018-05-30 09:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_auto_20180530_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 5, 30, 12, 50, 3, 398144), null=True),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='date_printed',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 5, 30, 12, 50, 3, 398144), null=True),
        ),
    ]
