# Generated by Django 2.0.4 on 2018-05-30 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_auto_20180530_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='date_printed',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
