# Generated by Django 2.0.4 on 2018-05-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_auto_20180530_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='date_printed',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
